In [1]:
#%run 'word2vec_data.ipynb'
import cPickle as pickle
%pylab inline

import scipy
import numpy as np
import pandas as pd
#import plotly.plotly as py
import matplotlib.pyplot as plt

import nltk
from nltk.corpus import stopwords

from gensim import models


import math
import codecs
import re
import string
from time import time


## Sklearn
from sklearn import svm, datasets, preprocessing, metrics
import sklearn

from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.metrics import roc_curve, auc, precision_recall_curve, average_precision_score, roc_auc_score, accuracy_score
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support, accuracy_score, precision_score
from sklearn.utils import shuffle


from sklearn.svm import SVC
from sklearn import datasets, feature_selection, cluster, feature_extraction, decomposition, metrics, model_selection
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split, cross_val_score

from sklearn.feature_extraction.text import TfidfVectorizer, HashingVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.svm import LinearSVC
from scipy import interp

#############################

#############################
### other stuff
from IPython import display

import os
#import ipyparallel as ipp
import warnings
warnings.filterwarnings('ignore')

# This is here to avoid all the Matplotlib warnings due to current bugs 
# - not a good idea to keep around
print ("Required Libraries loaded.")

Populating the interactive namespace from numpy and matplotlib
Required Libraries loaded.


C:\Users\CR107\Anaconda2\lib\site-packages\gensim\utils.py:855: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
#!pip install --upgrade version_information
#%reload_ext version_information
%load_ext version_information 
%version_information scipy, numpy, sklearn, pandas, scipy, nltk, gensim, matplotlib

Software versions
Python 2.7.13 64bit [MSC v.1500 64 bit (AMD64)]
IPython 5.1.0
OS Windows 7 6.1.7601 SP1
scipy 0.18.1
numpy 1.11.3
sklearn 0.18.1
pandas 0.19.2
scipy 0.18.1
nltk 3.2.2
gensim 1.0.1
matplotlib 1.5.1
Tue Apr 04 13:25:58 2017 GMT Daylight Time

In [3]:
inhibitor  = pd.read_csv("C:/EPC_Data/complete_data/raw/AtypicalAntipsychotics.csv", sep=",", index_col = "PMID")

In [4]:
seed = 29
# shuffle dataset and split to train and test
inhibitor = shuffle(inhibitor, random_state = seed)
inhibitor.head(2)

study  EndNote_Id init_screen fin_screen  \
PMID                                                                  
9004341   AtypicalAntipsychotics        2978           5          E   
11156810  AtypicalAntipsychotics         420           6          E   

                                                   Abstract  \
PMID                                                          
9004341    1. The purpose of this retrospective chart re...   
11156810   The authors examined the relationship between...   

                                                       MeSH  \
PMID                                                          
9004341    Adolescent Adult Age Factors Antipsychotic Ag...   
11156810   Adult Ambulatory Care Facilities Antipsychoti...   

                                                    Mh_MeSH  \
PMID                                                          
9004341   [MHAdolescent, MHAdult, MHAge, MHFactors, MHAn...   
11156810  [MHAdult, MHAmbulatory, MHCare, MHFacilities, ...   

                                                Pt_Pub_Type  \
PMID                                                          
9004341   [PTClinical, PTTrial, PTJournal, PTArticle, PT...   
11156810  [PTJournal, PTArticle, PTResearch, PTSupport,,...   

                                                   Pub_Type  \
PMID                                                          
9004341    Clinical Trial Journal Article Randomized Con...   
11156810   Journal Article Research Support, Non-U.S. Gov't   

                                                      TiAbs  \
PMID                                                          
9004341   Clozapine eligibility: the effect of stringent...   
11156810  Clozapine-associated reduction in arrest rates...   

                                                TiAbsMeSHPT  \
PMID                                                          
9004341   Clozapine eligibility: the effect of stringent...   
11156810  Clozapine-associated reduction in arrest rates...   

                                         TiAbsMeSHPT_append  \
PMID                                                          
9004341   Clozapine eligibility: the effect of stringent...   
11156810  Clozapine-associated reduction in arrest rates...   

                                           TiAbsMeSH_append  \
PMID                                                          
9004341   Clozapine eligibility: the effect of stringent...   
11156810  Clozapine-associated reduction in arrest rates...   

                                                  TiAbsMesh  \
PMID                                                          
9004341   Clozapine eligibility: the effect of stringent...   
11156810  Clozapine-associated reduction in arrest rates...   

                                                      Title  Label  
PMID                                                                
9004341   Clozapine eligibility: the effect of stringent...      0  
11156810  Clozapine-associated reduction in arrest rates...      0

In [5]:
folder = "C:/EPC_Data/complete_data/word2vec"
filepath = os.path.join(folder, "AtypicalAntipsychotics_chi2_features_10minwords_15context")
model = models.Word2Vec.load(filepath)
print ("\nMatrix of word vectors is size : ", model.wv.syn0.shape)

('\nMatrix of word vectors is size : ', (2124L, 381L))


In [6]:
#Create feature vectors from the averages of word vectors

def makeFeatureVec(words, model):
    """
    words - list of words (i.e. article) to be used as input for the creation of word vectors
    model - model to use for the creation of the vectors
    
    makeFeatureVec: Function to average all of the word vectors in a given paragraph
    returns: a numpy array of floats that are the average of the constituent word vectors for each word
    """
    num_features = model.wv.syn0.shape[1]
    featureVec = np.zeros((num_features,),dtype="float32")
    nwords = 0.
    # 
    # Index2word is a list that contains the names of the words in 
    # the model's vocabulary. Convert it to a set, for speed 
    index2word_set = set(model.wv.index2word)
    #
    # Loop over each word in the article and, if it is in the model's
    # vocaublary, add its feature vector to the total
    for word in words:
        if word in index2word_set: 
            nwords = nwords + 1.
            featureVec = np.add(featureVec,model[word])
    # 
    # Divide the result by the number of words to get the average
    featureVec = np.divide(featureVec,nwords)
    return featureVec

def getAvgFeatureVecs(articles, model):
    """
    articles - list of articles for which the creation of word vectors needs to be done for each
    model - model to use for the creation of the vectors
    
    getAvgFeatureVecs: Given a set of articles (each one a list of words), calculate 
    the average feature vector for each one and return a 2D numpy array 
    returns: a 2D numpy array that contains the average of the constituent word vectors for each article
    """
    num_features = model.wv.syn0.shape[1]
    articleFeatureVecs = np.zeros((len(articles),num_features),dtype="float32")
    counter = 0.
    
    # Loop through the articles
    for article in articles:
        #
        # Print a status message every 1000th review
        if counter%500. == 0.:
            print ("Article %d of %d" % (counter, len(articles)))
        # 
        # Call the function (defined above) that makes average feature vectors
        articleFeatureVecs[counter] = makeFeatureVec(article, model)
        #
        # Increment the counter
        counter = counter + 1.
    return articleFeatureVecs

In [7]:
# Import articles for string cleaning

def clean_text(text, stem_words = False, remove_stopwords = False):
    ###clean
    texts = re.sub("[^a-zA-Z]",    #pattern to match
              " ",              #replace other with this
              str(text))                 #text to apply to
         
    #print "Text recived: ", texts 
    clean_corpus = texts.lower().split()
    #print "corpus: ", clean_corpus
    if stem_words:
        # Porter stemmer
        porter = nltk.PorterStemmer()
        # Snowball stemmer
        snowball = nltk.SnowballStemmer('english')
        # Lancaster stemmer
        lancaster = nltk.LancasterStemmer()
        # General stemming Lambda function to stem tokens
        clean_corpus = lambda tokens: [porter.stem(w) for w in corpus]
    if remove_stopwords:   # Optionally remove stop words
        stops = set(stopwords.words("english"))
        clean_corpus = [w for w in clean_corpus if not w in stops]
        #print "Clean_corpus: ", clean_corpus
    
    return (clean_corpus)

In [8]:
# ****************************************************************
# Calculate average feature vectors for training and testing sets,
# using the functions we defined above. We remove stopwords.

print ("Creating average feature vecs for articles")
cleaned_articles = []
for article in inhibitor.TiAbsMesh:
    cleaned_articles.append(clean_text(article, stem_words=False, remove_stopwords=True ))

averageWordVecs = getAvgFeatureVecs(cleaned_articles, model)

Creating average feature vecs for articles
Article 0 of 1120
Article 500 of 1120
Article 1000 of 1120


In [9]:
RANDOM_STATE = 55
TEST_SIZE = 0.3

X_train, X_test, y_train, y_test = train_test_split(averageWordVecs, inhibitor.Label, test_size=TEST_SIZE, 
                                                    random_state=37)

print (len(X_train))
print (len(X_test))

784
336


In [10]:
X = averageWordVecs
y = inhibitor.Label
le = preprocessing.LabelEncoder()
y  = le.fit_transform(y)
yTrFreq = scipy.stats.itemfreq(inhibitor.Label)
print(yTrFreq)

[[  0 974]
 [  1 146]]


In [11]:
def weight(x):
    x = np.where(x==0, 1, 4)
    return x 

In [12]:
# Set the parameters by cross-validation
tuned_parameters = [{'kernel': ['rbf', "sigmoid"], 'gamma': [1e-3, 1e-4],
                     'class_weight':['balanced', None],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000], 'class_weight':['balanced', None]}]

scores = ['recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(SVC(), tuned_parameters, cv=2, scoring='%s_macro' % score)
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(metrics.classification_report(y_true, y_pred))
    print()

# Tuning hyper-parameters for recall
()
Best parameters set found on development set:
()
{'kernel': 'sigmoid', 'C': 1000, 'gamma': 0.001, 'class_weight': 'balanced'}
()
Grid scores on development set:
()
0.500 (+/-0.000) for {'kernel': 'rbf', 'C': 1, 'gamma': 0.001, 'class_weight': 'balanced'}
0.500 (+/-0.000) for {'kernel': 'sigmoid', 'C': 1, 'gamma': 0.001, 'class_weight': 'balanced'}
0.500 (+/-0.000) for {'kernel': 'rbf', 'C': 1, 'gamma': 0.0001, 'class_weight': 'balanced'}
0.500 (+/-0.000) for {'kernel': 'sigmoid', 'C': 1, 'gamma': 0.0001, 'class_weight': 'balanced'}
0.500 (+/-0.000) for {'kernel': 'rbf', 'C': 1, 'gamma': 0.001, 'class_weight': None}
0.500 (+/-0.000) for {'kernel': 'sigmoid', 'C': 1, 'gamma': 0.001, 'class_weight': None}
0.500 (+/-0.000) for {'kernel': 'rbf', 'C': 1, 'gamma': 0.0001, 'class_weight': None}
0.500 (+/-0.000) for {'kernel': 'sigmoid', 'C': 1, 'gamma': 0.0001, 'class_weight': None}
0.500 (+/-0.000) for {'kernel': 'rbf', 'C': 10, 'gamma': 0.001, 'class_w

In [13]:
clf = SVC(C=1000.0, cache_size=200, class_weight='balanced', coef0=0.0,decision_function_shape=None, degree=3, 
          gamma='auto', kernel='sigmoid', max_iter=-1, probability=False, random_state=55, shrinking=True,
          tol=0.001, verbose=False)

seeds = [35, 71, 21, 61, 55]

svm_precision = []
svm_recall = []
svm_f = []
acc = []
ps_vectors = []
ns_vectors = []
tr_pos = []
tr_neg = []
te_pos = []
te_neg = []
true_pos = []
true_neg = []
false_pos = []
false_neg = []


for i in range(0, 5):
    
    seed = seeds[i]   
    skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=seed)

    for train_index, test_index in skf.split(X, y):
        
           
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        w = weight(y_train)

        yTrFreq = scipy.stats.itemfreq(y_train)
        tr_pos = np.append(tr_pos, yTrFreq[1][1])
        tr_neg = np.append(tr_neg, yTrFreq[0][1])

        # print(yTrFreq)

        yTrFreq = scipy.stats.itemfreq(y_test)
        te_pos = np.append(te_pos, yTrFreq[1][1])
        te_neg = np.append(te_neg, yTrFreq[0][1])

        #print(yTrFreq)

        print ("Fitting for Seed = %d" % seed)  

        clf.fit(X_train, y_train, sample_weight = w)

        pred = clf.predict(X_test)

        s_vector = clf.n_support_


        s_prec = metrics.precision_score(y_test, pred)#, sample_weight=wt)
        s_recall = metrics.recall_score(y_test, pred)#, sample_weight=wt)
        s_f1 = metrics.f1_score(y_test, pred)#, sample_weight=wt)

        print (metrics.confusion_matrix(y_test, pred))
        true_neg.append(metrics.confusion_matrix(y_test, pred)[0,0])
        true_pos.append(metrics.confusion_matrix(y_test, pred)[1,1])
        false_neg.append(metrics.confusion_matrix(y_test, pred)[1, 0])
        false_pos.append(metrics.confusion_matrix(y_test, pred)[0, 1])

        acc_s = metrics.accuracy_score(y_test, pred)
        svm_precision.append(s_prec)
        svm_recall.append(s_recall)
        svm_f.append(s_f1)
        acc.append(acc_s)
        ps_vectors = np.append(ps_vectors, s_vector[1])
        ns_vectors = np.append(ns_vectors, s_vector[0])      

print ("SVM Cross validation results: ")
print ("Mean Precision: %.2f +/- %.2f "%(np.mean(svm_precision), np.std(svm_precision)))
print ("  Mean  Recall: %.2f +/- %.2f" %(np.mean(svm_recall), np.std(svm_recall)))
print ("      Mean  F1: %.2f +/- %.2f" %(np.mean(svm_f), np.std(svm_f)))
print ("Mean  Accuracy: %.2f +/- %.2f" %(np.mean(acc), np.std(acc)))
print (" True Negative: ", true_neg)
print ("False Negative: ", false_neg)
print (" True Positive: ", true_pos)
print ("False Positive: ", false_pos)
print ("Negative support Vectors: ", ns_vectors)
print ("Positive support Vectors: ", ps_vectors)
print ("Mean positive support vectors: %.2f +/- %.2f"%(np.mean(ps_vectors), np.std(ps_vectors)))
print ("Mean Negative support vectors: %.2f +/- %.2f"%(np.mean(ns_vectors), np.std(ns_vectors)))
print ("Train positive: %.2f" %(np.mean(tr_pos)))
print ("Train negattive: %.2f" %(np.mean(tr_neg)))
print ("Test positive: %.2f" %(np.mean(te_pos)))
print ("Test negative: %.2f" %(np.mean(te_neg)))

Fitting for Seed = 35
[[ 18 469]
 [  0  73]]
Fitting for Seed = 35
[[ 56 431]
 [  1  72]]
Fitting for Seed = 71
[[ 96 391]
 [  2  71]]
Fitting for Seed = 71
[[  0 487]
 [  0  73]]
Fitting for Seed = 21
[[ 91 396]
 [  5  68]]
Fitting for Seed = 21
[[  0 487]
 [  0  73]]
Fitting for Seed = 61
[[  1 486]
 [  0  73]]
Fitting for Seed = 61
[[ 51 436]
 [  1  72]]
Fitting for Seed = 55
[[142 345]
 [  6  67]]
Fitting for Seed = 55
[[  0 487]
 [  0  73]]
SVM Cross validation results: 
Mean Precision: 0.14 +/- 0.01 
  Mean  Recall: 0.98 +/- 0.03
      Mean  F1: 0.25 +/- 0.02
Mean  Accuracy: 0.21 +/- 0.08
(' True Negative: ', [18, 56, 96, 0, 91, 0, 1, 51, 142, 0])
('False Negative: ', [0, 1, 2, 0, 5, 0, 0, 1, 6, 0])
(' True Positive: ', [73, 72, 71, 73, 68, 73, 73, 72, 67, 73])
('False Positive: ', [469, 431, 391, 487, 396, 487, 486, 436, 345, 487])
('Negative support Vectors: ', array([ 487.,  479.,  467.,  487.,  467.,  487.,  487.,  480.,  433.,  487.]))
('Positive support Vectors: ', array([ 

In [14]:
clf = SVC(C=1000.0, cache_size=200, class_weight='balanced', coef0=0.0,decision_function_shape=None, degree=3, 
          gamma='auto', kernel='rbf', max_iter=-1, probability=False, random_state=55, shrinking=True,
          tol=0.001, verbose=False)

seeds = [35, 71, 21, 61, 55]

svm_precision = []
svm_recall = []
svm_f = []
acc = []
ps_vectors = []
ns_vectors = []
tr_pos = []
tr_neg = []
te_pos = []
te_neg = []
true_pos = []
true_neg = []
false_pos = []
false_neg = []


for i in range(0, 5):
    
    seed = seeds[i]   
    skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=seed)

    for train_index, test_index in skf.split(X, y):
        
           
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        w = weight(y_train)

        yTrFreq = scipy.stats.itemfreq(y_train)
        tr_pos = np.append(tr_pos, yTrFreq[1][1])
        tr_neg = np.append(tr_neg, yTrFreq[0][1])

        # print(yTrFreq)

        yTrFreq = scipy.stats.itemfreq(y_test)
        te_pos = np.append(te_pos, yTrFreq[1][1])
        te_neg = np.append(te_neg, yTrFreq[0][1])

        #print(yTrFreq)

        print ("Fitting for Seed = %d" % seed)  

        clf.fit(X_train, y_train, sample_weight = w)

        pred = clf.predict(X_test)

        s_vector = clf.n_support_


        s_prec = metrics.precision_score(y_test, pred)#, sample_weight=wt)
        s_recall = metrics.recall_score(y_test, pred)#, sample_weight=wt)
        s_f1 = metrics.f1_score(y_test, pred)#, sample_weight=wt)

        print (metrics.confusion_matrix(y_test, pred))
        true_neg.append(metrics.confusion_matrix(y_test, pred)[0,0])
        true_pos.append(metrics.confusion_matrix(y_test, pred)[1,1])
        false_neg.append(metrics.confusion_matrix(y_test, pred)[1, 0])
        false_pos.append(metrics.confusion_matrix(y_test, pred)[0, 1])

        acc_s = metrics.accuracy_score(y_test, pred)
        svm_precision.append(s_prec)
        svm_recall.append(s_recall)
        svm_f.append(s_f1)
        acc.append(acc_s)
        ps_vectors = np.append(ps_vectors, s_vector[1])
        ns_vectors = np.append(ns_vectors, s_vector[0])  
print ("SVM Cross validation results: ")
print ("Mean Precision: %.2f +/- %.2f "%(np.mean(svm_precision), np.std(svm_precision)))
print ("  Mean  Recall: %.2f +/- %.2f" %(np.mean(svm_recall), np.std(svm_recall)))
print ("      Mean  F1: %.2f +/- %.2f" %(np.mean(svm_f), np.std(svm_f)))
print ("Mean  Accuracy: %.2f +/- %.2f" %(np.mean(acc), np.std(acc)))
print (" True Negative: ", true_neg)
print ("False Negative: ", false_neg)
print (" True Positive: ", true_pos)
print ("False Positive: ", false_pos)
print ("Negative support Vectors: ", ns_vectors)
print ("Positive support Vectors: ", ps_vectors)
print ("Mean positive support vectors: %.2f +/- %.2f"%(np.mean(ps_vectors), np.std(ps_vectors)))
print ("Mean Negative support vectors: %.2f +/- %.2f"%(np.mean(ns_vectors), np.std(ns_vectors)))
print ("Train positive: %.2f" %(np.mean(tr_pos)))
print ("Train negattive: %.2f" %(np.mean(tr_neg)))
print ("Test positive: %.2f" %(np.mean(te_pos)))
print ("Test negative: %.2f" %(np.mean(te_neg)))

Fitting for Seed = 35
[[ 50 437]
 [  1  72]]
Fitting for Seed = 35
[[ 81 406]
 [  2  71]]
Fitting for Seed = 71
[[109 378]
 [  3  70]]
Fitting for Seed = 71
[[  0 487]
 [  0  73]]
Fitting for Seed = 21
[[101 386]
 [  4  69]]
Fitting for Seed = 21
[[  0 487]
 [  0  73]]
Fitting for Seed = 61
[[ 35 452]
 [  0  73]]
Fitting for Seed = 61
[[ 67 420]
 [  1  72]]
Fitting for Seed = 55
[[154 333]
 [  7  66]]
Fitting for Seed = 55
[[  0 487]
 [  0  73]]
SVM Cross validation results: 
Mean Precision: 0.14 +/- 0.01 
  Mean  Recall: 0.98 +/- 0.03
      Mean  F1: 0.25 +/- 0.02
Mean  Accuracy: 0.23 +/- 0.09
(' True Negative: ', [50, 81, 109, 0, 101, 0, 35, 67, 154, 0])
('False Negative: ', [1, 2, 3, 0, 4, 0, 0, 1, 7, 0])
(' True Positive: ', [72, 71, 70, 73, 69, 73, 73, 72, 66, 73])
('False Positive: ', [437, 406, 378, 487, 386, 487, 452, 420, 333, 487])
('Negative support Vectors: ', array([ 484.,  475.,  455.,  487.,  456.,  487.,  487.,  476.,  416.,  487.]))
('Positive support Vectors: ', array

In [15]:
clf = SVC(C=1000.0, cache_size=200, class_weight='balanced', coef0=0.0,decision_function_shape=None, degree=3, 
          gamma='auto', kernel='linear', max_iter=-1, probability=False, random_state=55, shrinking=True,
          tol=0.001, verbose=False)

seeds = [35, 71, 21, 61, 55]

svm_precision = []
svm_recall = []
svm_f = []
acc = []
ps_vectors = []
ns_vectors = []
tr_pos = []
tr_neg = []
te_pos = []
te_neg = []
true_pos = []
true_neg = []
false_pos = []
false_neg = []


for i in range(0, 5):
    
    seed = seeds[i]   
    skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=seed)

    for train_index, test_index in skf.split(X, y):
        
           
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        w = weight(y_train)

        yTrFreq = scipy.stats.itemfreq(y_train)
        tr_pos = np.append(tr_pos, yTrFreq[1][1])
        tr_neg = np.append(tr_neg, yTrFreq[0][1])

        # print(yTrFreq)

        yTrFreq = scipy.stats.itemfreq(y_test)
        te_pos = np.append(te_pos, yTrFreq[1][1])
        te_neg = np.append(te_neg, yTrFreq[0][1])

        #print(yTrFreq)

        print ("Fitting for Seed = %d" % seed)  

        clf.fit(X_train, y_train, sample_weight = w)

        pred = clf.predict(X_test)

        s_vector = clf.n_support_


        s_prec = metrics.precision_score(y_test, pred)#, sample_weight=wt)
        s_recall = metrics.recall_score(y_test, pred)#, sample_weight=wt)
        s_f1 = metrics.f1_score(y_test, pred)#, sample_weight=wt)

        print (metrics.confusion_matrix(y_test, pred))
        true_neg.append(metrics.confusion_matrix(y_test, pred)[0,0])
        true_pos.append(metrics.confusion_matrix(y_test, pred)[1,1])
        false_neg.append(metrics.confusion_matrix(y_test, pred)[1, 0])
        false_pos.append(metrics.confusion_matrix(y_test, pred)[0, 1])

        acc_s = metrics.accuracy_score(y_test, pred)
        svm_precision.append(s_prec)
        svm_recall.append(s_recall)
        svm_f.append(s_f1)
        acc.append(acc_s)
        ps_vectors = np.append(ps_vectors, s_vector[1])
        ns_vectors = np.append(ns_vectors, s_vector[0])    

print ("SVM Cross validation results: ")
print ("Mean Precision: %.2f +/- %.2f "%(np.mean(svm_precision), np.std(svm_precision)))
print ("  Mean  Recall: %.2f +/- %.2f" %(np.mean(svm_recall), np.std(svm_recall)))
print ("      Mean  F1: %.2f +/- %.2f" %(np.mean(svm_f), np.std(svm_f)))
print ("Mean  Accuracy: %.2f +/- %.2f" %(np.mean(acc), np.std(acc)))
print (" True Negative: ", true_neg)
print ("False Negative: ", false_neg)
print (" True Positive: ", true_pos)
print ("False Positive: ", false_pos)
print ("Negative support Vectors: ", ns_vectors)
print ("Positive support Vectors: ", ps_vectors)
print ("Mean positive support vectors: %.2f +/- %.2f"%(np.mean(ps_vectors), np.std(ps_vectors)))
print ("Mean Negative support vectors: %.2f +/- %.2f"%(np.mean(ns_vectors), np.std(ns_vectors)))
print ("Train positive: %.2f" %(np.mean(tr_pos)))
print ("Train negattive: %.2f" %(np.mean(tr_neg)))
print ("Test positive: %.2f" %(np.mean(te_pos)))
print ("Test negative: %.2f" %(np.mean(te_neg)))

Fitting for Seed = 35
[[155 332]
 [  8  65]]
Fitting for Seed = 35
[[194 293]
 [  7  66]]
Fitting for Seed = 71
[[202 285]
 [  7  66]]
Fitting for Seed = 71
[[112 375]
 [  1  72]]
Fitting for Seed = 21
[[176 311]
 [  7  66]]
Fitting for Seed = 21
[[126 361]
 [  8  65]]
Fitting for Seed = 61
[[133 354]
 [  2  71]]
Fitting for Seed = 61
[[162 325]
 [  5  68]]
Fitting for Seed = 55
[[254 233]
 [ 12  61]]
Fitting for Seed = 55
[[ 53 434]
 [  0  73]]
SVM Cross validation results: 
Mean Precision: 0.17 +/- 0.02 
  Mean  Recall: 0.92 +/- 0.05
      Mean  F1: 0.29 +/- 0.02
Mean  Accuracy: 0.40 +/- 0.09
(' True Negative: ', [155, 194, 202, 112, 176, 126, 133, 162, 254, 53])
('False Negative: ', [8, 7, 7, 1, 7, 8, 2, 5, 12, 0])
(' True Positive: ', [65, 66, 66, 72, 66, 65, 71, 68, 61, 73])
('False Positive: ', [332, 293, 285, 375, 311, 361, 354, 325, 233, 434])
('Negative support Vectors: ', array([ 435.,  406.,  392.,  461.,  391.,  440.,  448.,  427.,  320.,  479.]))
('Positive support Vectors